# Generated by Django 3.2.7 on 2021-09-13 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Building', '0009_auto_20210913_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_no', models.CharField(max_length=10, verbose_name='Nr mieszkania')),
                ('area', models.PositiveIntegerField(verbose_name='Powierzchnia w m2')),
                ('ownership_type', models.SmallIntegerField(choices=[(1, 'Pełna własność'), (2, 'Spółdzielcze'), (3, 'Komunalne')], verbose_name='Typ własności')),
                ('heating_type', models.SmallIntegerField(choices=[(1, 'CO'), (2, 'Gazowe'), (3, 'Elektryczne'), (4, 'Węglowe')], verbose_name='Typ ogrzewania')),
                ('natural_gas', models.BooleanField(default=True, verbose_name='Gaz')),
                ('electricity', models.BooleanField(default=True, verbose_name='Prąd')),
                ('water', models.BooleanField(default=True, verbose_name='Woda')),
                ('water_heating', models.BooleanField(default=True, verbose_name='Podgrzewanie wody z CO')),
                ('building', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Building.building', verbose_name='Building')),
            ],
            options={
                'verbose_name': 'Mieszkanie',
                'verbose_name_plural': 'Mieszkania',
            },
        ),
    ]
