# Generated by Django 3.2.7 on 2021-09-15 16:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Flat', '0002_auto_20210913_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='user',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL, verbose_name='Mieszkańcy'),
        ),
    ]
