# Generated by Django 3.2.7 on 2021-09-15 16:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Flat', '0003_alter_flat_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL, verbose_name='Mieszkańcy'),
        ),
    ]
