# Generated by Django 3.2.7 on 2021-09-15 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Building', '0009_auto_20210913_1128'),
        ('Flat', '0004_alter_flat_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='area',
            field=models.PositiveIntegerField(null=True, verbose_name='Powierzchnia w m2'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Building.building', verbose_name='Budynek'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='floor',
            field=models.SmallIntegerField(null=True, verbose_name='Piętro'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='heating_type',
            field=models.SmallIntegerField(choices=[(1, 'CO'), (2, 'Gazowe'), (3, 'Elektryczne'), (4, 'Węglowe')], default=1, verbose_name='Typ ogrzewania'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='ownership_type',
            field=models.SmallIntegerField(choices=[(1, 'Pełna własność'), (2, 'Spółdzielcze'), (3, 'Komunalne')], default=1, verbose_name='Typ własności'),
        ),
    ]
