# Generated by Django 3.2.7 on 2021-09-15 17:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Flat', '0005_auto_20210915_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='flat_no',
        ),
        migrations.AddField(
            model_name='flat',
            name='number',
            field=models.PositiveIntegerField(default=1, verbose_name='Nr mieszkania'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flat',
            name='number_suffix',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M')], default=None, max_length=1, null=True, verbose_name='Suffix'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Mieszkańcy'),
        ),
    ]
