# Generated by Django 3.2.7 on 2021-09-26 11:45

import Building.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=100, verbose_name='Ulica')),
                ('number', models.CharField(max_length=5, verbose_name='Number budynku')),
                ('city', models.CharField(max_length=100, verbose_name='Miasto')),
                ('zip_code', models.CharField(max_length=6, verbose_name='Kod pocztowy')),
                ('no_of_flats', models.PositiveIntegerField(verbose_name='Ilość mieszkań w budynku')),
                ('picture', models.ImageField(blank=True, upload_to='images/buildings/', verbose_name='Zdjęcie budynku')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Budynek',
                'verbose_name_plural': 'Budynki',
                'ordering': ('street', 'number'),
            },
        ),
        migrations.CreateModel(
            name='Cartography',
            fields=[
                ('parcel_identification_number', models.CharField(max_length=30, verbose_name='Identyfikator działki')),
                ('parcel_precinct', models.SmallIntegerField(choices=[(1, 'Północ'), (2, 'Południe'), (3, 'Zachód'), (4, 'Wschód')], verbose_name='Obręb')),
                ('parcel_number', models.CharField(max_length=20, verbose_name='Numer działki')),
                ('building', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Building.building', verbose_name='Budynek')),
            ],
            options={
                'verbose_name': 'Dane kartograficzne',
                'verbose_name_plural': 'Dane kartograficzne',
            },
        ),
        migrations.CreateModel(
            name='HousingCooperative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa zarządcy/wspólnoty')),
                ('street', models.CharField(max_length=100, null=True, verbose_name='Ulica')),
                ('number', models.CharField(max_length=10, null=True, verbose_name='Numer')),
                ('city', models.CharField(max_length=100, null=True, verbose_name='Miasto')),
                ('zip_code', models.CharField(max_length=6, null=True, verbose_name='Kod pocztowy')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images/coop_logo/', verbose_name='Logotyp zarzadcy/wspólnoty')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=12, null=True, verbose_name='Nr telefonu')),
                ('website', models.URLField(blank=True)),
                ('president', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Prezes')),
            ],
            options={
                'verbose_name': 'Wspólnota/Zarządca',
                'verbose_name_plural': 'Wspólnoty/Zarządcy',
            },
        ),
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Nr mieszkania')),
                ('number_suffix', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M')], default=None, max_length=1, null=True, verbose_name='Suffix')),
                ('area', models.PositiveIntegerField(blank=True, null=True, verbose_name='Powierzchnia w m2')),
                ('floor', models.SmallIntegerField(blank=True, null=True, verbose_name='Piętro')),
                ('ownership_type', models.SmallIntegerField(choices=[(1, 'Pełna własność'), (2, 'Spółdzielcze'), (3, 'Komunalne')], default=1, verbose_name='Typ własności')),
                ('heating_type', models.SmallIntegerField(choices=[(1, 'CO'), (2, 'Gazowe'), (3, 'Elektryczne'), (4, 'Węglowe')], default=1, verbose_name='Typ ogrzewania')),
                ('water_heating', models.BooleanField(default=True, verbose_name='Podgrzewanie wody z CO')),
                ('natural_gas', models.BooleanField(default=True, verbose_name='Gaz')),
                ('electricity', models.BooleanField(default=True, verbose_name='Prąd')),
                ('water', models.BooleanField(default=True, verbose_name='Woda')),
                ('slug', models.SlugField(unique=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Building.building', verbose_name='Budynek')),
                ('user', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mieszkanie',
                'verbose_name_plural': 'Mieszkania',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='BuildingPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, upload_to='images/buildings/from_users/', verbose_name='Zdjęcie budynku')),
                ('picture_description', models.CharField(max_length=255, verbose_name='Opis zdjęcia')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Building.building')),
            ],
            options={
                'verbose_name': 'Zdjęcie nieruchomości',
                'verbose_name_plural': 'Zdjęcia nieruchomości',
            },
        ),
        migrations.CreateModel(
            name='BuildingDocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(blank=True, upload_to='documents/buildings/', validators=[Building.validators.MaxSizeValidator(1)], verbose_name='Zdjęcie budynku')),
                ('document_description', models.CharField(max_length=255, verbose_name='Opis dokumentu')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Building.building')),
            ],
            options={
                'verbose_name': 'Dokument nieruchomości',
                'verbose_name_plural': 'Dokumenty nieruchomości',
            },
        ),
        migrations.AddField(
            model_name='building',
            name='housing_cooperative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Building.housingcooperative', verbose_name='Wspólnota/zarządca'),
        ),
    ]
