# Generated by Django 3.2.7 on 2021-09-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Building', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartography',
            name='parcel_precinct',
            field=models.SmallIntegerField(choices=[(1, 'Północ'), (2, 'Południe'), (3, 'Zachód'), (4, 'Wschód')]),
        ),
    ]
