# Generated by Django 3.2.7 on 2021-09-23 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Building', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='slug',
            new_name='slug_building',
        ),
        migrations.RenameField(
            model_name='flat',
            old_name='slug',
            new_name='slug_flat',
        ),
    ]
