# Generated by Django 3.2.7 on 2021-09-12 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Building', '0002_alter_cartography_parcel_precinct'),
    ]

    operations = [
        migrations.AddField(
            model_name='housingcooperative',
            name='building',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Building.building'),
        ),
    ]
