# Generated by Django 3.2.7 on 2021-09-27 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Building', '0003_auto_20210927_0802'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measure',
            options={'verbose_name': 'Wskazania licznika', 'verbose_name_plural': 'Wskazania liczników'},
        ),
        migrations.AlterModelOptions(
            name='paymentperiod',
            options={'ordering': ('year', 'month'), 'verbose_name': 'Okres rozliczeniowy', 'verbose_name_plural': 'Okresy rozliczeniowe'},
        ),
        migrations.RemoveField(
            model_name='flat',
            name='measure',
        ),
        migrations.AddField(
            model_name='measure',
            name='flat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Building.flat', verbose_name='Mieszkanie'),
        ),
    ]
