# Generated by Django 3.2.7 on 2021-09-23 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Building', '0003_auto_20210923_1659'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'ordering': ('street', 'number'), 'verbose_name': 'Budynek', 'verbose_name_plural': 'Budynki'},
        ),
        migrations.RenameField(
            model_name='building',
            old_name='building_no',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='building',
            old_name='building_picture',
            new_name='picture',
        ),
    ]
