# Generated by Django 3.2.7 on 2021-09-12 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Building', '0003_housingcooperative_building'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='roof_keys_keeper',
        ),
        migrations.RemoveField(
            model_name='housingcooperative',
            name='building',
        ),
        migrations.AddField(
            model_name='building',
            name='housing_cooperative',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Building.housingcooperative'),
        ),
    ]
