# Generated by Django 3.2.7 on 2021-09-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Building', '0004_auto_20210927_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measure',
            name='energy',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Prąd'),
        ),
        migrations.AlterField(
            model_name='measure',
            name='gas',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Gaz'),
        ),
        migrations.AlterField(
            model_name='measure',
            name='water',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Woda'),
        ),
    ]
