# Generated by Django 3.2.7 on 2021-09-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Building', '0004_auto_20210912_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
