# Generated by Django 3.2.7 on 2021-09-13 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Building', '0006_alter_building_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='housingcooperative',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='housingcooperative',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='housingcooperative',
            name='logo',
            field=models.ImageField(null=True, upload_to='images/coop_logo/'),
        ),
        migrations.AddField(
            model_name='housingcooperative',
            name='number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='housingcooperative',
            name='street',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='housingcooperative',
            name='zip_code',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='building_no',
            field=models.CharField(max_length=5, verbose_name='Number budynku'),
        ),
        migrations.AlterField(
            model_name='building',
            name='building_picture',
            field=models.ImageField(upload_to='images/', verbose_name='Zdjęcie budynku'),
        ),
        migrations.AlterField(
            model_name='building',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Miasto'),
        ),
        migrations.AlterField(
            model_name='building',
            name='housing_cooperative',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Building.housingcooperative', verbose_name='Wspólnota/zarządca'),
        ),
        migrations.AlterField(
            model_name='building',
            name='no_of_flats',
            field=models.PositiveIntegerField(verbose_name='Ilość mieszkań w budynku'),
        ),
        migrations.AlterField(
            model_name='building',
            name='street',
            field=models.CharField(max_length=100, verbose_name='Ulica'),
        ),
        migrations.AlterField(
            model_name='building',
            name='zip_code',
            field=models.CharField(max_length=6, verbose_name='Kod pocztowy'),
        ),
    ]
