# Generated by Django 3.2.7 on 2021-09-25 17:03

import Building.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Building', '0006_alter_buildingphotos_building'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingdocs',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Building.building'),
        ),
        migrations.AlterField(
            model_name='buildingdocs',
            name='document',
            field=models.FileField(blank=True, upload_to='documents/buildings/', validators=[Building.validators.MaxSizeValidator(1)], verbose_name='Zdjęcie budynku'),
        ),
    ]
