# Generated by Django 3.2.7 on 2021-09-29 19:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Building', '0006_auto_20210928_2317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flat',
            old_name='slug',
            new_name='slug_flat',
        ),
        migrations.AddField(
            model_name='flat',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='housingcooperative',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/coop_logo/', verbose_name='Logotyp zarządcy/wspólnoty'),
        ),
    ]
