# Generated by Django 3.2.7 on 2021-09-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Building', '0007_auto_20210913_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='housingcooperative',
            name='phone',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
