# Generated by Django 3.2.7 on 2021-09-13 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Building', '0008_housingcooperative_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'verbose_name': 'Budynek', 'verbose_name_plural': 'Budynki'},
        ),
        migrations.AlterModelOptions(
            name='cartography',
            options={'verbose_name': 'Dane kartograficzne', 'verbose_name_plural': 'Dane kartograficzne'},
        ),
        migrations.AlterModelOptions(
            name='housingcooperative',
            options={'verbose_name': 'Wspólnota/Zarządca', 'verbose_name_plural': 'Wspólnoty/Zarządcy'},
        ),
        migrations.AlterField(
            model_name='cartography',
            name='building',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Building.building', verbose_name='Budynek'),
        ),
        migrations.AlterField(
            model_name='cartography',
            name='parcel_identification_number',
            field=models.CharField(max_length=30, verbose_name='Identyfikator działki'),
        ),
        migrations.AlterField(
            model_name='cartography',
            name='parcel_number',
            field=models.CharField(max_length=20, verbose_name='Numer działki'),
        ),
        migrations.AlterField(
            model_name='cartography',
            name='parcel_precinct',
            field=models.SmallIntegerField(choices=[(1, 'Północ'), (2, 'Południe'), (3, 'Zachód'), (4, 'Wschód')], verbose_name='Obręb'),
        ),
        migrations.AlterField(
            model_name='housingcooperative',
            name='city',
            field=models.CharField(max_length=100, null=True, verbose_name='Miasto'),
        ),
        migrations.AlterField(
            model_name='housingcooperative',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='housingcooperative',
            name='logo',
            field=models.ImageField(null=True, upload_to='images/coop_logo/', verbose_name='Logotyp zarzadcy/wspólnoty'),
        ),
        migrations.AlterField(
            model_name='housingcooperative',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nazwa zarządcy/wspólnoty'),
        ),
        migrations.AlterField(
            model_name='housingcooperative',
            name='number',
            field=models.CharField(max_length=10, null=True, verbose_name='Numer'),
        ),
        migrations.AlterField(
            model_name='housingcooperative',
            name='phone',
            field=models.CharField(max_length=12, null=True, verbose_name='Nr telefonu'),
        ),
        migrations.AlterField(
            model_name='housingcooperative',
            name='president',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Prezes'),
        ),
        migrations.AlterField(
            model_name='housingcooperative',
            name='street',
            field=models.CharField(max_length=100, null=True, verbose_name='Ulica'),
        ),
        migrations.AlterField(
            model_name='housingcooperative',
            name='zip_code',
            field=models.CharField(max_length=6, null=True, verbose_name='Kod pocztowy'),
        ),
    ]
