# Generated by Django 3.2.7 on 2021-09-15 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Building', '0009_auto_20210913_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Nr mieszkania')),
                ('number_suffix', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M')], default=None, max_length=1, null=True, verbose_name='Suffix')),
                ('area', models.PositiveIntegerField(blank=True, null=True, verbose_name='Powierzchnia w m2')),
                ('floor', models.SmallIntegerField(blank=True, null=True, verbose_name='Piętro')),
                ('ownership_type', models.SmallIntegerField(choices=[(1, 'Pełna własność'), (2, 'Spółdzielcze'), (3, 'Komunalne')], default=1, verbose_name='Typ własności')),
                ('heating_type', models.SmallIntegerField(choices=[(1, 'CO'), (2, 'Gazowe'), (3, 'Elektryczne'), (4, 'Węglowe')], default=1, verbose_name='Typ ogrzewania')),
                ('natural_gas', models.BooleanField(default=True, verbose_name='Gaz')),
                ('electricity', models.BooleanField(default=True, verbose_name='Prąd')),
                ('water', models.BooleanField(default=True, verbose_name='Woda')),
                ('water_heating', models.BooleanField(default=True, verbose_name='Podgrzewanie wody z CO')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Building.building', verbose_name='Budynek')),
                ('user', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Mieszkańcy')),
            ],
            options={
                'verbose_name': 'Mieszkanie',
                'verbose_name_plural': 'Mieszkania',
            },
        ),
    ]
