# Generated by Django 3.2.7 on 2021-09-17 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Building', '0010_flat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'ordering': ('street', 'building_no'), 'verbose_name': 'Budynek', 'verbose_name_plural': 'Budynki'},
        ),
    ]
