# Generated by Django 3.2.7 on 2021-09-23 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Building', '0011_alter_building_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='user',
        ),
    ]
