# Generated by Django 3.2.7 on 2021-09-15 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Building', '0010_flat'),
        ('User', '0002_auto_20210915_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='building',
            field=models.ManyToManyField(blank=True, to='Building.Building'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='flat',
            field=models.ManyToManyField(blank=True, to='Building.Flat'),
        ),
    ]
