# Generated by Django 3.2.7 on 2021-09-29 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_profile_flat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='flat',
        ),
    ]
