# Generated by Django 3.2.7 on 2021-09-19 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_auto_20210917_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='token',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
