# Generated by Django 3.2.7 on 2021-09-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_alter_profile_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contact_flag',
            field=models.BooleanField(default=True),
        ),
    ]
