# Generated by Django 3.2.7 on 2021-09-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_profile_contact_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(null=True, upload_to='images/user/avatars/', verbose_name='Avatar użytkownika'),
        ),
    ]
