# Generated by Django 3.2.7 on 2021-09-23 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_profile_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='phoneNumber',
            new_name='phone_number',
        ),
    ]
