# Generated by Django 3.2.7 on 2021-09-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_rename_phonenumber_profile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images/user/avatars/', verbose_name='Avatar użytkownika'),
        ),
    ]
